input {
  file {
    path => "/usr/share/logstash/logs/logs.json"
    start_position => "beginning"
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs"
  }
  stdout { codec => rubydebug }
}
